export const UI_SELECTORS = {
  NAV: {
    PRODUCTS_LINK: 'nav-products-link',
    PURCHASES_LINK: 'nav-purchases-link',
    MASTER_DATA_LINK: 'nav-master-data-link',
    ORDERS_LINK: 'nav-orders-link',
    CUSTOMERS_LINK: 'nav-customers-link',
    LABELS_LINK: 'nav-labels-link',
  },
  PRODUCTS: {
    LIST: {
      CREATE_BTN: 'products-create-btn',
      SEARCH_INPUT: 'products-search-input',
      SORT_SELECT: 'products-sort-select',
      TABLE: 'products-table',
      ROW: (id: string) => `product-row-${id}`,
      NAME_CELL: (id: string) => `product-name-${id}`,
      PRICE_CELL: (id: string) => `product-price-${id}`,
      COST_CELL: (id: string) => `product-cost-${id}`,
      BOM_BADGE: (id: string) => `product-bom-badge-${id}`,
      WARNING_ICON: (id: string) => `product-warning-icon-${id}`,
      TOOLTIP: (id: string) => `product-tooltip-${id}`,
      PROFIT_BADGE: (id: string) => `product-profit-badge-${id}`,
      EDIT_BTN: (id: string) => `product-edit-btn-${id}`,
      DELETE_BTN: (id: string) => `product-delete-btn-${id}`,
    },
    CREATE: {
      NAME_INPUT: 'product-name-input',
      PRICE_INPUT: 'product-price-input',
      COST_INPUT: 'product-cost-input',
      WEIGHT_INPUT: 'product-weight-input',
      FRAGRANCE_LOAD_INPUT: 'product-fragrance-load-input',
      CONTAINER_SELECT: 'product-container-select',
      WAX_SELECT: 'product-wax-select',
      ADD_WAX_BTN: 'product-add-wax-btn',
      WAX_PCT_INPUT: (index: number) => `product-wax-pct-${index}`,
      FRAGRANCE_SELECT: 'product-fragrance-select',
      ADD_FRAGRANCE_BTN: 'product-add-fragrance-btn',
      FRAGRANCE_PCT_INPUT: (index: number) => `product-fragrance-pct-${index}`,
      PREVIEW_BOM_COST: 'product-preview-bom-cost',
      PREVIEW_PROFIT: 'product-preview-profit',
      WARNING_BANNER: 'product-preview-warning-banner',
      SAVE_BTN: 'product-save-btn',
      CANCEL_BTN: 'product-cancel-btn',
    },
  },
  PURCHASES: {
    RECORD_BTN: 'purchases-record-btn',
    CATEGORY_WAX_BTN: 'purchase-category-wax-btn',
    CATEGORY_FRAGRANCE_BTN: 'purchase-category-fragrance-btn',
    CATEGORY_CONTAINER_BTN: 'purchase-category-container-btn',
    MATERIAL_TYPE_SELECT: 'purchase-material-type-select',
    MATERIAL_ID_SELECT: 'purchase-material-id-select',
    QUANTITY_INPUT: 'purchase-quantity-input',
    UNIT_SELECT: 'purchase-unit-select',
    TOTAL_COST_INPUT: 'purchase-total-cost-input',
    SUPPLIER_INPUT: 'purchase-supplier-input',
    NOTES_INPUT: 'purchase-notes-input',
    SUBMIT_BTN: 'purchase-submit-btn',
    TABLE: 'purchases-table',
    ROW: (id: string) => `purchase-row-${id}`,
  },
  MASTER_DATA: {
    TAB_WAXES: 'tab-waxes',
    TAB_FRAGRANCES: 'tab-fragrances',
    TAB_CONTAINERS: 'tab-containers',
    ADD_BTN: 'master-data-add-btn',
    NAME_INPUT: 'master-data-name-input',
    SUBMIT_BTN: 'master-data-submit-btn',
    TABLE: 'master-data-table',
    ROW: (id: string) => `master-data-row-${id}`,
    TOGGLE_STATUS_BTN: (id: string) => `master-data-toggle-${id}`,
  },
  CUSTOMERS: {
    LIST: {
      CREATE_BTN: 'customers-create-btn',
      SEARCH_INPUT: 'customers-search-input',
      TABLE: 'customers-table',
      ROW: (id: string) => `customer-row-${id}`,
      NAME_CELL: (id: string) => `customer-name-${id}`,
      PHONE_CELL: (id: string) => `customer-phone-${id}`,
      EDIT_BTN: (id: string) => `customer-edit-btn-${id}`,
    },
    FORM: {
      NAME_INPUT: 'customer-name-input',
      PHONE_INPUT: 'customer-phone-input',
      EMAIL_INPUT: 'customer-email-input',
      ADDRESS_INPUT: 'customer-address-input',
      SAVE_BTN: 'customer-save-btn',
      CANCEL_BTN: 'customer-cancel-btn',
    },
  },
  ORDERS: {
    LIST: {
      CREATE_BTN: 'orders-create-btn',
      STATUS_FILTER: 'orders-status-filter',
      TABLE: 'orders-table',
      ROW: (id: string) => `order-row-${id}`,
      STATUS_BADGE: (id: string) => `order-status-${id}`,
    },
    CREATE: {
      CUSTOMER_PHONE_INPUT: 'order-customer-phone-input',
      CUSTOMER_NAME_INPUT: 'order-customer-name-input',
      CUSTOMER_EMAIL_INPUT: 'order-customer-email-input',
      CUSTOMER_ADDRESS_INPUT: 'order-customer-address-input',
      CUSTOMER_SELECT: 'order-customer-select',
      PRODUCT_SELECT: 'order-product-select',
      QUANTITY_INPUT: 'order-quantity-input',
      ADD_ITEM_BTN: 'order-add-item-btn',
      SAVE_BTN: 'order-save-btn',
      CANCEL_BTN: 'order-cancel-btn',
      TOTAL_PRICE: 'order-total-price',
    },
    DETAIL: {
      STATUS_SELECT: 'order-detail-status-select',
      CANCEL_BTN: 'order-detail-cancel-btn',
      CANCEL_REASON_INPUT: 'order-detail-cancel-reason-input',
      CONFIRM_CANCEL_BTN: 'order-detail-confirm-cancel-btn',
      PROFIT_BADGE: 'order-detail-profit-badge',
    },
  },
  LABELS: {
    LIST: {
      CREATE_BTN: 'labels-create-btn',
      TABLE: 'labels-table',
      ROW: (id: string) => `label-row-${id}`,
    },
    DESIGNER: {
      NAME_INPUT: 'label-name-input',
      CANVAS: 'label-canvas',
      ADD_TEXT_BTN: 'label-add-text-btn',
      PLACEHOLDER_SELECT: 'label-placeholder-select',
      SAVE_BTN: 'label-save-btn',
      CANCEL_BTN: 'label-cancel-btn',
    },
  },
};
