export const UI_SELECTORS = {
  NAV: {
    PRODUCTS_LINK: 'nav-products-link',
    PURCHASES_LINK: 'nav-purchases-link',
    MASTER_DATA_LINK: 'nav-master-data-link',
    ORDERS_LINK: 'nav-orders-link',
  },
  PRODUCTS: {
    LIST: {
      CREATE_BTN: 'products-create-btn',
      SEARCH_INPUT: 'products-search-input',
      SORT_SELECT: 'products-sort-select',
      TABLE: 'products-table',
      ROW: (id: string) => `product-row-${id}`,
      NAME_CELL: (id: string) => `product-name-${id}`,
      PRICE_CELL: (id: string) => `product-price-${id}`,
      COST_CELL: (id: string) => `product-cost-${id}`,
      BOM_BADGE: (id: string) => `product-bom-badge-${id}`,
      WARNING_ICON: (id: string) => `product-warning-icon-${id}`,
      TOOLTIP: (id: string) => `product-tooltip-${id}`,
      PROFIT_BADGE: (id: string) => `product-profit-badge-${id}`,
      EDIT_BTN: (id: string) => `product-edit-btn-${id}`,
      DELETE_BTN: (id: string) => `product-delete-btn-${id}`,
    },
    CREATE: {
      NAME_INPUT: 'product-name-input',
      PRICE_INPUT: 'product-price-input',
      COST_INPUT: 'product-cost-input',
      WEIGHT_INPUT: 'product-weight-input',
      FRAGRANCE_LOAD_INPUT: 'product-fragrance-load-input',
      CONTAINER_SELECT: 'product-container-select',
      WAX_SELECT: 'product-wax-select',
      ADD_WAX_BTN: 'product-add-wax-btn',
      WAX_PCT_INPUT: (index: number) => `product-wax-pct-${index}`,
      FRAGRANCE_SELECT: 'product-fragrance-select',
      ADD_FRAGRANCE_BTN: 'product-add-fragrance-btn',
      FRAGRANCE_PCT_INPUT: (index: number) => `product-fragrance-pct-${index}`,
      PREVIEW_BOM_COST: 'product-preview-bom-cost',
      PREVIEW_PROFIT: 'product-preview-profit',
      WARNING_BANNER: 'product-preview-warning-banner',
      SAVE_BTN: 'product-save-btn',
      CANCEL_BTN: 'product-cancel-btn',
    },
  },
  PURCHASES: {
    MATERIAL_TYPE_SELECT: 'purchase-material-type-select',
    MATERIAL_ID_SELECT: 'purchase-material-id-select',
    QUANTITY_INPUT: 'purchase-quantity-input',
    UNIT_SELECT: 'purchase-unit-select',
    TOTAL_COST_INPUT: 'purchase-total-cost-input',
    SUPPLIER_INPUT: 'purchase-supplier-input',
    NOTES_INPUT: 'purchase-notes-input',
    SUBMIT_BTN: 'purchase-submit-btn',
    TABLE: 'purchases-table',
    ROW: (id: string) => `purchase-row-${id}`,
  },
  MASTER_DATA: {
    TAB_WAXES: 'tab-waxes',
    TAB_FRAGRANCES: 'tab-fragrances',
    TAB_CONTAINERS: 'tab-containers',
    ADD_BTN: 'master-data-add-btn',
    NAME_INPUT: 'master-data-name-input',
    SUBMIT_BTN: 'master-data-submit-btn',
  },
};

